local Standard = require('ship_types/Standard')
local Assault = require('ship_types/Assault')
local Gunship = require('ship_types/Gunship')
local Ray = require('ship_types/Ray')
local Zap = require('ship_types/Zap')
local Charge = require('ship_types/Charge')
local Missile = require('ship_types/Missile')
local Miner = require('ship_types/Miner')
local Spreader = require('ship_types/Spreader')
local Phaser = require('ship_types/Phaser')
local Shockwave = require('ship_types/Shockwave')
local Bounce = require('ship_types/Bounce')
local Vortex = require('ship_types/Vortex')

ShipType = {
  standard = {
    name = "Standard",
    actionHandler = Standard,
    topSpeed = 240,
    acceleration = 360,
    rotationSpeed = 8,
    fireRate = 12,
    health = 150,
    weaponDamage = 10,
    frameOffset = 0,
    previousType = "vortex",
    nextType = "gunship"
  },
  gunship = {
    name = "Gunship",
    actionHandler = Gunship,
    topSpeed = 120,
    acceleration = 180,
    rotationSpeed = 5,
    cannonRotation = 0,
    fireRate = 1.5,
    health = 130,
    weaponDamage = 40,
    frameOffset = 2,
    previousType = "standard",
    nextType = "assalt"
  },
  assalt = {
    name = "Assault",
    actionHandler = Assault,
    topSpeed = 300,
    acceleration = 400,
    rotationSpeed = 5,
    fireRate = 1,
    health = 170,
    weaponDamage = 10,
    frameOffset = 4,
    previousType = "gunship",
    nextType = "ray"
  },
  ray = {
    name = "Ray",
    actionHandler = Ray,
    topSpeed = 180,
    acceleration = 240,
    rotationSpeed = 4,
    fireRate = 20,
    health = 150,
    weaponDamage = 3,
    frameOffset = 6,
    previousType = "assalt",
    nextType = "zap"
  },
  zap = {
    name = "Zapper",
    actionHandler = Zap,
    topSpeed = 180,
    acceleration = 180,
    rotationSpeed = 5,
    fireRate = 2,
    health = 160,
    weaponDamage = 3,
    frameOffset = 8,
    previousType = "ray",
    nextType = "charge"
  },
  charge = {
    name = "Charger",
    actionHandler = Charge,
    topSpeed = 240,
    acceleration = 240,
    rotationSpeed = 4,
    fireRate = 4,
    health = 160,
    weaponDamage = 20,
    frameOffset = 10,
    previousType = "zap",
    nextType = "missile"
  },
  missile = {
    name = "Missile",
    actionHandler = Missile,
    topSpeed = 180,
    acceleration = 180,
    rotationSpeed = 4,
    fireRate = 1,
    health = 150,
    weaponDamage = 30,
    frameOffset = 12,
    previousType = "charge",
    nextType = "miner"
  },
  miner = {
    name = "Miner",
    actionHandler = Miner,
    topSpeed = 200,
    acceleration = 200,
    rotationSpeed = 4,
    fireRate = 1,
    health = 150,
    weaponDamage = 10,
    frameOffset = 14,
    previousType = "missile",
    nextType = "spreader"
  },
  spreader = {
    name = "Spreader",
    actionHandler = Spreader,
    topSpeed = 240,
    acceleration = 360,
    rotationSpeed = 10,
    fireRate = 4,
    health = 150,
    weaponDamage = 5,
    frameOffset = 0,
    previousType = "miner",
    nextType = "phaser"
  },
  phaser = {
    name = "Phaser",
    actionHandler = Phaser,
    topSpeed = 240,
    acceleration = 360,
    rotationSpeed = 10,
    fireRate = 1,
    health = 150,
    weaponDamage = 100,
    frameOffset = 0,
    previousType = "spreader",
    nextType = "standard"
  },
  shockwave = {
    name = "Shockwave",
    actionHandler = Shockwave,
    topSpeed = 240,
    acceleration = 360,
    rotationSpeed = 10,
    fireRate = 1,
    health = 150,
    weaponDamage = 100,
    frameOffset = 0,
    previousType = "phaser",
    nextType = "bounce"
  },
  bounce = {
    name = "Bounce",
    actionHandler = Bounce,
    topSpeed = 200,
    acceleration = 260,
    rotationSpeed = 5,
    fireRate = 2,
    health = 150,
    weaponDamage = 20,
    frameOffset = 0,
    previousType = "shockwave",
    nextType = "standard"
  },
  vortex = {
    name = "Vortex",
    actionHandler = Vortex,
    topSpeed = 200,
    acceleration = 260,
    rotationSpeed = 5,
    fireRate = 1,
    health = 150,
    weaponDamage = 40,
    frameOffset = 0,
    previousType = "bounce",
    nextType = "standard"
  },
}